version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "09:00"
      timezone: America/Sao_Paulo
    assignees:
      - rtrampox
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      timezone: America/Sao_Paulo
    assignees:
      - rtrampox
