name: Setup workflow
description: Composite action that sets up bun with cache and install packages

inputs:
  install-args:
    description: "Additional arguments to pass to bun install"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Setup bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: Setup bun
      uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun i --ignore-scripts --frozen-lockfile ${{ inputs.install-args }}
      shell: bash
